import type { Train, TrainDetail, TelemetrySnapshot } from "./types";

export const MOCK_TRAINS: Train[] = [
  {
    id: "KZ8A-019",
    model: "KZ8A",
    status: "warning",
    healthScore: 65,
    speed: 89,
    position: { lng: 63.6, lat: 50.3 },
    route: "Aktobe — Kyzylorda",
    lastSeen: "11:42",
  },
  {
    id: "KZ9A-005",
    model: "KZ8A",
    status: "normal",
    healthScore: 51,
    speed: 10,
    position: { lng: 76.9, lat: 51.2 },
    route: "Astana — Semey",
    lastSeen: "11:42",
  },
  {
    id: "TE33A-047",
    model: "TE33A",
    status: "critical",
    healthScore: 72,
    speed: 61,
    position: { lng: 68.5, lat: 46.8 },
    route: "Shymkent — Kyzylorda",
    lastSeen: "11:42",
  },
  {
    id: "TE33A-031",
    model: "TE33A",
    status: "warning",
    healthScore: 58,
    speed: 45,
    position: { lng: 75.4, lat: 43.5 },
    route: "Almaty — Balkhash",
    lastSeen: "11:42",
  },
  {
    id: "KZ3A-012",
    model: "KZ8A",
    status: "normal",
    healthScore: 88,
    speed: 98,
    position: { lng: 66.8, lat: 44.5 },
    route: "Kyzylorda — Shymkent",
    lastSeen: "11:42",
  },
  {
    id: "TE33A-018",
    model: "TE33A",
    status: "normal",
    healthScore: 93,
    speed: 0,
    position: { lng: 69.6, lat: 42.8 },
    route: "Shymkent — Karaganda",
    lastSeen: "11:42",
  },
  {
    id: "KZ8A-007",
    model: "KZ8A",
    status: "no_signal",
    healthScore: 0,
    speed: 0,
    position: { lng: 80.2, lat: 44.0 },
    route: "Almaty — Druzhba",
    lastSeen: "11:30",
  },
];

export const MOCK_TRAIN_DETAIL: Record<string, TrainDetail> = {
  "TE33A-047": {
    id: "TE33A-047",
    model: "TE33A",
    status: "critical",
    healthScore: 72,
    speed: 61,
    position: { lng: 68.5, lat: 46.8 },
    route: "Shymkent — Kyzylorda",
    lastSeen: "11:42",
    serialNumber: "TE33A-2019-047",
    operatorName: "KTZ Freight",
    mode: "HAUL",
    startedAt: "09:14",
  },
  "KZ8A-019": {
    id: "KZ8A-019",
    model: "KZ8A",
    status: "warning",
    healthScore: 65,
    speed: 89,
    position: { lng: 63.6, lat: 50.3 },
    route: "Aktobe — Kyzylorda",
    lastSeen: "11:42",
    serialNumber: "KZ8A-2021-019",
    operatorName: "KTZ Passenger",
    mode: "HAUL",
    startedAt: "07:45",
  },
  "TE33A-031": {
    id: "TE33A-031",
    model: "TE33A",
    status: "warning",
    healthScore: 58,
    speed: 45,
    position: { lng: 75.4, lat: 43.5 },
    route: "Almaty — Balkhash",
    lastSeen: "11:42",
    serialNumber: "TE33A-2018-031",
    operatorName: "KTZ Freight",
    mode: "HAUL",
    startedAt: "08:30",
  },
  "KZ3A-012": {
    id: "KZ3A-012",
    model: "KZ8A",
    status: "normal",
    healthScore: 88,
    speed: 98,
    position: { lng: 66.8, lat: 44.5 },
    route: "Kyzylorda — Shymkent",
    lastSeen: "11:42",
    serialNumber: "KZ8A-2022-012",
    operatorName: "KTZ Passenger",
    mode: "HAUL",
    startedAt: "06:00",
  },
  "TE33A-018": {
    id: "TE33A-018",
    model: "TE33A",
    status: "normal",
    healthScore: 93,
    speed: 0,
    position: { lng: 69.6, lat: 42.8 },
    route: "Shymkent — Karaganda",
    lastSeen: "11:42",
    serialNumber: "TE33A-2017-018",
    operatorName: "KTZ Freight",
    mode: "IDLE",
    startedAt: "10:00",
  },
  "KZ9A-005": {
    id: "KZ9A-005",
    model: "KZ8A",
    status: "normal",
    healthScore: 51,
    speed: 10,
    position: { lng: 76.9, lat: 51.2 },
    route: "Astana — Semey",
    lastSeen: "11:42",
    serialNumber: "KZ8A-2020-005",
    operatorName: "KTZ Passenger",
    mode: "SHUNT",
    startedAt: "11:00",
  },
  "KZ8A-007": {
    id: "KZ8A-007",
    model: "KZ8A",
    status: "no_signal",
    healthScore: 0,
    speed: 0,
    position: { lng: 80.2, lat: 44.0 },
    route: "Almaty — Druzhba",
    lastSeen: "11:30",
    serialNumber: "KZ8A-2019-007",
    operatorName: "KTZ Freight",
    mode: "IDLE",
    startedAt: "08:00",
  },
};

export const MOCK_TELEMETRY: Record<string, TelemetrySnapshot> = {
  "TE33A-047": {
    ts: Date.now(),
    lat: 46.8,
    lon: 68.5,
    speed_kph: 61,
    heading_deg: 45,
    engine_temp_c: 98,
    oil_temp_c: 75,
    oil_pressure_ok: true,
    engine_rpm: 1450,
    fuel_level_pct: 62,
    fuel_consumption_rate: 210,
    brake_pipe_pressure_kpa: 410,
    main_reservoir_pressure_kpa: 860,
    brake_cylinder_pressure_kpa: 210,
    brake_pipe_leak_kpa_per_min: 0.4,
    brake_status: "APPLIED",
    current_a: 1245,
    traction_voltage_v: 3000,
    battery_voltage_v: 110,
    tractive_effort_kn: 195,
    dynamic_brake_force_kn: 0,
    health_index: 72,
    fault_codes: ["COOL_TEMP_HIGH", "BRAKE_PRESS_LOW"],
    alarm_status: 2,
    fire_temp_c: 24,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 12,
  },
  "KZ8A-019": {
    ts: Date.now(),
    lat: 50.3,
    lon: 63.6,
    speed_kph: 89,
    heading_deg: 112,
    engine_temp_c: 72,
    oil_temp_c: 58,
    oil_pressure_ok: true,
    engine_rpm: 1680,
    fuel_level_pct: 78,
    fuel_consumption_rate: 175,
    brake_pipe_pressure_kpa: 490,
    main_reservoir_pressure_kpa: 820,
    brake_cylinder_pressure_kpa: 180,
    brake_pipe_leak_kpa_per_min: 0.2,
    brake_status: "RELEASED",
    current_a: 980,
    traction_voltage_v: 25000,
    battery_voltage_v: 110,
    tractive_effort_kn: 155,
    dynamic_brake_force_kn: 0,
    health_index: 65,
    fault_codes: ["INV_TEMP_WARN"],
    alarm_status: 1,
    fire_temp_c: 22,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 45,
  },
  "TE33A-031": {
    ts: Date.now(),
    lat: 43.5,
    lon: 75.4,
    speed_kph: 45,
    heading_deg: 200,
    engine_temp_c: 84,
    oil_temp_c: 68,
    oil_pressure_ok: false,
    engine_rpm: 1200,
    fuel_level_pct: 45,
    fuel_consumption_rate: 165,
    brake_pipe_pressure_kpa: 390,
    main_reservoir_pressure_kpa: 780,
    brake_cylinder_pressure_kpa: 170,
    brake_pipe_leak_kpa_per_min: 1.2,
    brake_status: "APPLIED",
    current_a: 820,
    traction_voltage_v: 3000,
    battery_voltage_v: 108,
    tractive_effort_kn: 140,
    dynamic_brake_force_kn: 0,
    health_index: 58,
    fault_codes: ["OIL_PRESS_LOW", "BRAKE_LEAK"],
    alarm_status: 1,
    fire_temp_c: 23,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 28,
  },
  "KZ3A-012": {
    ts: Date.now(),
    lat: 44.5,
    lon: 66.8,
    speed_kph: 98,
    heading_deg: 160,
    engine_temp_c: 68,
    oil_temp_c: 52,
    oil_pressure_ok: true,
    engine_rpm: 0,
    fuel_level_pct: 91,
    fuel_consumption_rate: 0,
    brake_pipe_pressure_kpa: 500,
    main_reservoir_pressure_kpa: 900,
    brake_cylinder_pressure_kpa: 195,
    brake_pipe_leak_kpa_per_min: 0.1,
    brake_status: "RELEASED",
    current_a: 1100,
    traction_voltage_v: 25000,
    battery_voltage_v: 110,
    tractive_effort_kn: 180,
    dynamic_brake_force_kn: 0,
    health_index: 88,
    fault_codes: [],
    alarm_status: 0,
    fire_temp_c: 21,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 5,
  },
  "TE33A-018": {
    ts: Date.now(),
    lat: 42.8,
    lon: 69.6,
    speed_kph: 0,
    heading_deg: 0,
    engine_temp_c: 42,
    oil_temp_c: 38,
    oil_pressure_ok: true,
    engine_rpm: 600,
    fuel_level_pct: 85,
    fuel_consumption_rate: 28,
    brake_pipe_pressure_kpa: 500,
    main_reservoir_pressure_kpa: 920,
    brake_cylinder_pressure_kpa: 200,
    brake_pipe_leak_kpa_per_min: 0.0,
    brake_status: "RELEASED",
    current_a: 120,
    traction_voltage_v: 3000,
    battery_voltage_v: 111,
    tractive_effort_kn: 0,
    dynamic_brake_force_kn: 0,
    health_index: 93,
    fault_codes: [],
    alarm_status: 0,
    fire_temp_c: 20,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 0,
  },
  "KZ9A-005": {
    ts: Date.now(),
    lat: 51.2,
    lon: 76.9,
    speed_kph: 10,
    heading_deg: 270,
    engine_temp_c: 55,
    oil_temp_c: 44,
    oil_pressure_ok: true,
    engine_rpm: 0,
    fuel_level_pct: 70,
    fuel_consumption_rate: 0,
    brake_pipe_pressure_kpa: 480,
    main_reservoir_pressure_kpa: 840,
    brake_cylinder_pressure_kpa: 190,
    brake_pipe_leak_kpa_per_min: 0.1,
    brake_status: "RELEASED",
    current_a: 250,
    traction_voltage_v: 25000,
    battery_voltage_v: 110,
    tractive_effort_kn: 40,
    dynamic_brake_force_kn: 0,
    health_index: 51,
    fault_codes: [],
    alarm_status: 0,
    fire_temp_c: 22,
    comm_state: 1,
    pcs_open: false,
    alerter_timer_sec: 0,
  },
  "KZ8A-007": {
    ts: Date.now(),
    lat: 44.0,
    lon: 80.2,
    speed_kph: 0,
    heading_deg: 90,
    engine_temp_c: 35,
    oil_temp_c: 30,
    oil_pressure_ok: false,
    engine_rpm: 0,
    fuel_level_pct: 55,
    fuel_consumption_rate: 0,
    brake_pipe_pressure_kpa: 0,
    main_reservoir_pressure_kpa: 0,
    brake_cylinder_pressure_kpa: 0,
    brake_pipe_leak_kpa_per_min: 0,
    brake_status: "UNKNOWN",
    current_a: 0,
    traction_voltage_v: 0,
    battery_voltage_v: 98,
    tractive_effort_kn: 0,
    dynamic_brake_force_kn: 0,
    health_index: 0,
    fault_codes: ["COMM_LOST"],
    alarm_status: 3,
    fire_temp_c: 19,
    comm_state: 0,
    pcs_open: false,
    alerter_timer_sec: 0,
  },
};

export const MOCK_FLEET_STATS = {
  activeTrains: 24,
  activeDelta: 2,
  healthScore: 82,
  normalCount: 19,
  warningCount: 4,
  criticalCount: 1,
  liveStreamValue: 9842,
};

export const MOCK_TOP_RISK_TRAINS = [
  { id: "TE33A-047", issueKey: "r1" as const, score: 72 },
  { id: "KZ8A-019", issueKey: "r2" as const, score: 65 },
  { id: "TE33A-031", issueKey: "r3" as const, score: 58 },
];

export const MOCK_RECENT_EVENTS = [
  {
    time: "11:40",
    trainId: "TE33A-047",
    level: "critical" as const,
    value: "3.0",
  },
  { time: "11:37", trainId: "KZ8A-019", level: "warning" as const, value: "" },
  { time: "11:35", trainId: "TE33A-018", level: "info" as const, value: "" },
];
